[package]
name = "KBinsight"
version = "0.1.0"
authors = ["andrea"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "^0.8.0"
gdk = "0.12.1"
relm = "^0.19.0"
relm-derive = "^0.19.0"